# This is a draft! The project currently uses setup.py.

[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools"
]

[tool.poetry]
name = "ipyvizzu"
version = "0.15.0"
description = "Build animated charts in Jupyter Notebook and similar environments with a simple Python syntax"
license = "Apache-2.0"
authors = [{name = "David Vegh", email = "YOUR_EMAIL"}]
readme = "README.md"
repository = "https://github.com/vizzuhq/ipyvizzu"
documentation = "https://ipyvizzu.vizzuhq.com"
keywords = [
    "python",
    "chart",
    "charts",
    "dataviz",
    "jupyter",
    "animation",
    "ipython",
    "graphs",
    "storytelling",
    "jupyter-notebook",
    "data-visualization",
    "graphing",
    "plotting",
    "charting",
    "vizzu"
]
packages = [{ include = "ipyvizzu", from = "src/ipyvizzu" }, { include = "ipyvizzu.integrations" }]
classifiers = [
    "Environment :: Console",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3"
]
requires-python = ">=3.6"
dependencies = [
    "IPython",
    "jsonschema",
    "pandas",
    "fugue>=0.8.1"
]

[tool.poetry.urls]
"Tracker" = "https://github.com/vizzuhq/ipyvizzu/issues"
