site_name: ipyvizzu
site_url: https://vizzuhq.github.io/ipyvizzu/mkdocs

docs_dir: ../../docs

repo_url: https://github.com/vizzuhq/ipyvizzu
edit_uri: https://github.com/vizzuhq/ipyvizzu/edit/mkdocs/docs
use_directory_urls: false

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-white.svg
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/chart.css
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists

plugins:
  - search
  - section-index
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [../../src]
          options:
            members_order: source
            show_root_heading: True
            show_root_members_full_path: True
            show_submodules: True
  - gen-files:
      scripts:
        - gen_files.py
  - literate-nav

nav:
  - Home: index.md
  - installation.md
  - Tutorial:
      - tutorial/index.md
      - Axes, title, tooltip: tutorial/axes_title_tooltip.md
      - Geometry: tutorial/geometry.md
      - Channels & legend: tutorial/channels_legend.md
      - Group/stack: tutorial/group_stack.md
      - Sorting: tutorial/sorting.md
      - Align & range: tutorial/align_range.md
      - Aggregate/drill-down: tutorial/aggregate_drilldown.md
      - Orientation, split & polar: tutorial/orientation_split_polar.md
      - Filtering & adding new records: tutorial/filter_add_new_records.md
      - Without coordinates & noop channel: tutorial/without_coordinates_noop_channel.md
      - Color palette & fonts: tutorial/color_palette_fonts.md
      - Chart layout: tutorial/chart_layout.md
      - Animation options: tutorial/animation_options.md
      - Events: tutorial/events.md
      - Shorthands & Store: tutorial/shorthands_store.md
  - Environments:
      - environments/index.md
      - Jupyter/IPython:
          - environments/jupyter/index.md
          - Jupyter Notebook: environments/jupyter/jupyternotebook.md
          - environments/jupyter/colab.md
          - environments/jupyter/databricks.md
          - DataCamp: environments/jupyter/datacamp.md
          - environments/jupyter/deepnote.md
          - JupyterLab: environments/jupyter/jupyterlab.md
          - JupyterLite: environments/jupyter/jupyterlite.md
          - environments/jupyter/kaggle.md
          - Mercury/mljar: environments/jupyter/mercury.md
          - environments/jupyter/mode.md
          - environments/jupyter/noteable.md
          - Voilà: environments/jupyter/voila.md
          - VSCode Python: environments/jupyter/vscode.md
      - environments/streamlit.md
      - environments/panel.md
  - Reference: reference/ipyvizzu/
