site_name: ipyvizzu
site_url: https://vizzuhq.github.io/ipyvizzu/mkdocs

docs_dir: ../../docs

repo_url: https://github.com/vizzuhq/ipyvizzu
edit_uri: https://github.com/vizzuhq/ipyvizzu/edit/mkdocs/docs
use_directory_urls: false

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-white.svg
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/chart.css
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists

plugins:
  - search
  - section-index
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [../../src]
          options:
            members_order: source
            show_root_heading: True
            show_root_members_full_path: True
            show_submodules: True
  - gen-files:
      scripts:
        - gen_files.py
  - literate-nav

nav:
  - Home: index.md
  - Documentation:
      - docs/index.md
      - docs/installation.md
      - Tutorial:
          - docs/tutorial/index.md
          - Axes, title, tooltip: docs/tutorial/axes_title_tooltip.md
          - Geometry: docs/tutorial/geometry.md
          - Channels & legend: docs/tutorial/channels_legend.md
          - Group/stack: docs/tutorial/group_stack.md
          - Sorting: docs/tutorial/sorting.md
          - Align & range: docs/tutorial/align_range.md
          - Aggregate/drill-down: docs/tutorial/aggregate_drilldown.md
          - Orientation, split & polar: docs/tutorial/orientation_split_polar.md
          - Filtering & adding new records: docs/tutorial/filter_add_new_records.md
          - Without coordinates & noop channel: docs/tutorial/without_coordinates_noop_channel.md
          - Color palette & fonts: docs/tutorial/color_palette_fonts.md
          - Chart layout: docs/tutorial/chart_layout.md
          - Animation options: docs/tutorial/animation_options.md
      - Environments:
          - docs/environments/index.md
          - Jupyter/IPython:
              - docs/environments/jupyter/index.md
              - Jupyter Notebook: docs/environments/jupyter/jupyternotebook.md
              - docs/environments/jupyter/colab.md
              - docs/environments/jupyter/databricks.md
              - DataCamp: docs/environments/jupyter/datacamp.md
              - docs/environments/jupyter/deepnote.md
              - JupyterLab: docs/environments/jupyter/jupyterlab.md
              - JupyterLite: docs/environments/jupyter/jupyterlite.md
              - docs/environments/jupyter/kaggle.md
              - Mercury/mljar: docs/environments/jupyter/mercury.md
              - docs/environments/jupyter/mode.md
              - docs/environments/jupyter/noteable.md
              - Voilà: docs/environments/jupyter/voila.md
              - VSCode Python: docs/environments/jupyter/vscode.md
          - docs/environments/streamlit.md
          - docs/environments/panel.md
  - Reference: reference/ipyvizzu/
