site_name: ipyvizzu
site_url: https://vizzuhq.github.io/ipyvizzu/mkdocs

docs_dir: ../../docs

repo_url: https://github.com/vizzuhq/ipyvizzu
edit_uri: https://github.com/vizzuhq/ipyvizzu/edit/mkdocs/docs
use_directory_urls: false

theme:
  name: material
  features:
    - toc.follow
    - navigation.top
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-white.svg
  favicon: assets/favicon.svg
  custom_dir: ./overrides

extra_css:
  - stylesheets/site.css
  - stylesheets/highlight.css
  - stylesheets/gallery.css
  - stylesheets/chart.css

extra_javascript:
  - //cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.7/build/highlight.min.js
  - //cdn.jsdelivr.net/npm/papaparse@5.3/papaparse.min.js
  - javascripts/highlight.js

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - mdx_truly_sane_lists
  - attr_list
  - md_in_html

plugins:
  - search
  - awesome-pages
  - section-index
  - literate-nav
  - autorefs
  - coverage:
      page_name: coverage
      html_report_dir: tests/coverage
  - mkdocstrings:
      handlers:
        python:
          paths: [../../src]
          options:
            members_order: source
            show_root_heading: True
            show_root_members_full_path: True
            show_submodules: True
  - gen-files:
      scripts:
        - gen_pages.py
        - gen_examples.py
        - gen_reference.py
  - mkdocs-jupyter:
      include: []
      ignore: []
      ignore_h1_titles: False
      include_source: True
      execute: True
      allow_errors: False
      kernel_name: .venv

nav:
  - Home: index.md
  - installation.md
  - Tutorial:
      - tutorial/index.md
      - Data: tutorial/data.md
      - Axes, title, tooltip: tutorial/axes_title_tooltip.md
      - Geometry: tutorial/geometry.md
      - Channels & legend: tutorial/channels_legend.md
      - Group/stack: tutorial/group_stack.md
      - Sorting: tutorial/sorting.md
      - Align & range: tutorial/align_range.md
      - Aggregate/drill-down: tutorial/aggregate_drilldown.md
      - Orientation, split & polar: tutorial/orientation_split_polar.md
      - Filtering & adding new records: tutorial/filter_add_new_records.md
      - Without coordinates & noop channel: tutorial/without_coordinates_noop_channel.md
      - Color palette & fonts: tutorial/color_palette_fonts.md
      - Chart layout: tutorial/chart_layout.md
      - Animation options: tutorial/animation_options.md
      - Events: tutorial/events.md
      - Shorthands & Store: tutorial/shorthands_store.md
      - Chart presets: tutorial/chart_presets.md
  - Environments:
      - environments/index.md
      - Jupyter/IPython:
          - environments/jupyter/index.md
          - Jupyter Notebook: environments/jupyter/jupyternotebook.md
          - environments/jupyter/colab.md
          - environments/jupyter/databricks.md
          - DataCamp: environments/jupyter/datacamp.md
          - environments/jupyter/deepnote.md
          - JupyterLab: environments/jupyter/jupyterlab.md
          - JupyterLite: environments/jupyter/jupyterlite.md
          - environments/jupyter/kaggle.md
          - Mercury/mljar: environments/jupyter/mercury.md
          - environments/jupyter/mode.md
          - environments/jupyter/noteable.md
          - Voilà: environments/jupyter/voila.md
          - VSCode Python: environments/jupyter/vscode.md
      - environments/streamlit.md
      - environments/panel.md
  - Examples:
      - examples/index.md
      - Preset charts: examples/presets/
      - Animated charts: examples/animated/
      - Static charts: examples/static/
      - Stories: examples/stories/
  - Reference: reference/ipyvizzu/
  - Development:
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Coverage report: coverage.md
