name: Build documentation

on:
  workflow_call:

jobs:
  build_doc:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: ./.venv_ipyvizzu
          key: venv-ipyvizzu-${{ github.run_id }}

      - uses: actions/cache@v3
        with:
          path: ./tests/coverage
          key: coverage-ipyvizzu-${{ inputs.run_id }}

      - name: Touch dev environment
        run: make touch-dev

      - name: Set Jupyter kernel
        run: make install-kernel

      - name: Checkout vizzu-lib
        uses: actions/checkout@v2
        with:
          repository: vizzuhq/vizzu-lib
          path: vizzu-lib

      - name: Build documentation
        run: make doc
